### ISSUE TITLE
Add shortcut for screenshotting and uploading the whole screen

### ISSUE THREAD

**Issue by svelle** [piranha771/AbloadPush#3]
As the title says just an additional hotkey like Ctrl + shift + 1 or something or Ctrl + print screen maybe.

**Comment by piranha771** [comment]
Implemented in commit: https://github.com/piranha771/AbloadPush/commit/4b8b386ea278d0dccdc465563c5c4ca31ec5c3b8

and https://github.com/piranha771/AbloadPush/commit/0ca140e2755a8b0c1c9019a520cbe10b640ca2c2
